create type user_role as enum ('user', 'admin');
create type item_type as enum ('production', 'packaging', 'sales');
create type display_unit as enum ('g', 'pcs');
create type purchase_unit as enum ('g', 'kg', 'viss', 'pcs');
create type purchase_status as enum ('draft', 'confirmed');
create type operation_type as enum ('production', 'packaging');

create table if not exists public.users (
  id integer generated by default as identity primary key,
  "openId" varchar(64) not null unique,
  name text,
  email varchar(320),
  "loginMethod" varchar(64),
  role user_role not null default 'user',
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now(),
  "lastSignedIn" timestamptz not null default now()
);

create table if not exists public.items (
  id integer generated by default as identity primary key,
  name varchar(180) not null,
  code varchar(64) unique,
  category varchar(100),
  "itemType" item_type not null,
  "displayUnit" display_unit not null,
  "gramsPerDisplayUnit" numeric(18,6) not null default 1,
  "minStockGrams" numeric(18,6) not null default 0,
  "costPerUnit" numeric(18,4),
  "effectiveFrom" date not null,
  "inactiveFrom" date,
  "sortOrder" integer not null default 0,
  "createdBy" integer references public.users(id),
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now()
);

create table if not exists public.purchases (
  id integer generated by default as identity primary key,
  "purchaseDate" date not null,
  "itemId" integer not null references public.items(id),
  "inputQuantity" numeric(18,6) not null,
  "inputUnit" purchase_unit not null,
  "quantityGrams" numeric(18,6) not null,
  "totalCost" numeric(18,2) not null,
  "unitCostPerGram" numeric(18,8) not null,
  status purchase_status not null default 'confirmed',
  "confirmedAt" timestamptz,
  note text,
  "createdBy" integer references public.users(id),
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now()
);

create table if not exists public.operations (
  id integer generated by default as identity primary key,
  "operationDate" date not null,
  "itemId" integer not null references public.items(id),
  "operationType" operation_type not null,
  "issuedQtyGrams" numeric(18,6) not null default 0,
  "returnQtyGrams" numeric(18,6) not null default 0,
  "damageQtyGrams" numeric(18,6) not null default 0,
  note text,
  "createdBy" integer references public.users(id),
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now(),
  unique ("operationDate", "itemId", "operationType")
);

create table if not exists public.shops (
  id integer generated by default as identity primary key,
  name varchar(180) not null unique,
  active boolean not null default true,
  "createdBy" integer references public.users(id),
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now()
);

create table if not exists public."shopItemPrices" (
  id integer generated by default as identity primary key,
  "shopId" integer not null references public.shops(id),
  "itemId" integer not null references public.items(id),
  "sellingPricePerUnit" numeric(18,2) not null,
  active boolean not null default true,
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now(),
  unique ("shopId", "itemId")
);

create table if not exists public."salesEntries" (
  id integer generated by default as identity primary key,
  "saleDate" date not null,
  "shopId" integer not null references public.shops(id),
  "itemId" integer not null references public.items(id),
  "produceQtyGrams" numeric(18,6) not null default 0,
  "sellQtyGrams" numeric(18,6) not null default 0,
  "sellingPricePerUnit" numeric(18,2) not null default 0,
  note text,
  "createdBy" integer references public.users(id),
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now(),
  unique ("saleDate", "shopId", "itemId")
);

create table if not exists public.recipes (
  id integer generated by default as identity primary key,
  name varchar(180) not null,
  "outputItemId" integer references public.items(id),
  "outputQuantityGrams" numeric(18,6) not null default 1,
  note text,
  active boolean not null default true,
  "createdBy" integer references public.users(id),
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now()
);

create table if not exists public."recipeLines" (
  id integer generated by default as identity primary key,
  "recipeId" integer not null references public.recipes(id) on delete cascade,
  "itemId" integer not null references public.items(id),
  "quantityGrams" numeric(18,6) not null
);

create index if not exists items_type_order_idx on public.items ("itemType", "sortOrder");
create index if not exists items_effective_idx on public.items ("effectiveFrom", "inactiveFrom");
create index if not exists purchases_date_item_idx on public.purchases ("purchaseDate", "itemId");
create index if not exists purchases_item_month_idx on public.purchases ("itemId", "purchaseDate");
create index if not exists operations_item_date_idx on public.operations ("itemId", "operationDate");
create index if not exists sales_item_date_idx on public."salesEntries" ("itemId", "saleDate");
create index if not exists recipe_lines_recipe_idx on public."recipeLines" ("recipeId");

create or replace function public.set_updated_at() returns trigger language plpgsql as $$
begin new."updatedAt" = now(); return new; end;
$$;

do $$
declare table_name text;
begin
  foreach table_name in array array['users','items','purchases','operations','shops','shopItemPrices','salesEntries','recipes'] loop
    execute format('drop trigger if exists set_updated_at on public.%I', table_name);
    execute format('create trigger set_updated_at before update on public.%I for each row execute function public.set_updated_at()', table_name);
  end loop;
end $$;

alter table public.users enable row level security;
alter table public.items enable row level security;
alter table public.purchases enable row level security;
alter table public.operations enable row level security;
alter table public.shops enable row level security;
alter table public."shopItemPrices" enable row level security;
alter table public."salesEntries" enable row level security;
alter table public.recipes enable row level security;
alter table public."recipeLines" enable row level security;

-- The Bakery ERP server uses the Supabase service-role key and enforces roles in tRPC.
-- No anon/authenticated policies are added by this migration, so browser clients cannot bypass the server authorization layer.
