alter table public.operations
  add column if not exists "openingOverrideQtyGrams" numeric(18,6),
  add column if not exists "openingReason" text;

alter table public."salesEntries"
  add column if not exists "openingOverrideQtyGrams" numeric(18,6),
  add column if not exists "openingReason" text;

create table if not exists public."dailyLocks" (
  id integer generated by default as identity primary key,
  "businessDate" date not null,
  "ledgerType" varchar(32) not null,
  locked boolean not null default false,
  "lockedBy" integer references public.users(id),
  "lockedAt" timestamptz,
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now(),
  unique ("businessDate", "ledgerType")
);

create table if not exists public."auditLogs" (
  id integer generated by default as identity primary key,
  action varchar(80) not null,
  "entityType" varchar(80) not null,
  "entityId" integer,
  "businessDate" date,
  details text,
  "createdBy" integer references public.users(id),
  "createdAt" timestamptz not null default now()
);

create index if not exists audit_logs_date_idx on public."auditLogs" ("businessDate", "createdAt");
alter table public."dailyLocks" enable row level security;
alter table public."auditLogs" enable row level security;

drop trigger if exists set_updated_at on public."dailyLocks";
create trigger set_updated_at before update on public."dailyLocks" for each row execute function public.set_updated_at();
